name: Lint
on:
  push:
    branches:
      - main
  pull_request:

concurrency:
  group: review-${{github.ref}}
  cancel-in-progress: true

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.20.8
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Run linter
        run: make lint
